### ISSUE TITLE
Not able to load app in Expo (iOS)

### ISSUE THREAD

**Issue by n1t1nv3rma** [aws-samples/aws-amplify-react-native-events-app-workshop#3]
ec2-user@f7da532866c1:/code$ yarn start -c    
yarn run v1.22.4
$ expo start -c
Starting project at /code
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Starting Metro Bundler on port 19001.
Your JavaScript transform cache is empty, rebuilding (this may take a minute).
Tunnel ready.

  exp://54.206.117.81:19000

.....

Getting following error on both App and Docker container

Unable to resolve "react-native-swipe-list-view" from "src/screens/HomeScreen.js"
Failed building JavaScript bundle.

**Comment by ykbryan** [comment]
Resolved.
Closing this issue.
