### ISSUE TITLE
Corrupt file contents in /code/amplify/.config/local-aws-info.json

### ISSUE THREAD

**Issue by prakash-mu** [aws-samples/aws-amplify-react-native-events-app-workshop#4]
When I use command "amplify push" after adding analytics, I get the below error:

`UPDATE_COMPLETE functioneventappfb982ea6PostConfirmation AWS::CloudFormation::Stack Thu May 21 2020 04:45:34 GMT+0000 (Coordinated Universal Time) 
⠏ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE amplify-eventapp-dev-112821 AWS::CloudFormation::Stack Thu May 21 2020 04:45:34 GMT+0000 (Coordinated Universal Time) 
⠼ Updating resources in the cloud. This may take a few minutes...**Error: Corrupt file contents in /code/amplify/.config/local-aws-info.json**
    at getConfigForEnv (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:462:17)
    at loadConfigurationForEnv (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:513:29)
    at Object.loadConfiguration (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/configuration-manager.js:499:24)
    at Object.aws.configureWithCreds (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws.js:18:45)
    at Object.getConfiguredAWSClient (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/index.js:60:13)
    at getS3Client (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-file-uploader.js:13:30)
    at uploadFiles (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/utils/trigger-file-uploader.js:19:28)
    at uploadAuthTriggerFiles (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/upload-auth-trigger-files.js:7:11)
    at Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js:71:11)
    at runMicrotasks (<anonymous>)
✖ An error occurred when pushing the resources to the cloud

Unable to upload trigger files to S3
An error occured during the push operation: Unable to upload trigger files to S3
ec2-user@7bbe1f6e7523:/code$`

**Comment by prakash-mu** [comment]
I think this is fixed now.

I re-executed "amplify init" and created a new environment (deva instead of dev) then did an "amplify push". 

`ec2-user@7bbe1f6e7523:/code$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Do you want to use an existing environment? No
? Enter a name for the environment deva
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use prakash
Adding backend environment deva to AWS Amplify Console app: d13mhr6ywtnjwx
⠴ Initializing project in the cloud...

CREATE_IN_PROGRESS UnauthRole                  AWS::IAM::Role             Thu May 21 2020 04:58:24 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
CREATE_IN_PROGRESS AuthRole                    AWS::IAM::Role             Thu May 21 2020 04:58:24 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
CREATE_IN_PROGRESS UnauthRole                  AWS::IAM::Role             Thu May 21 2020 04:58:23 GMT+0000 (Coordinated Universal Time)                            
CREATE_IN_PROGRESS DeploymentBucket            AWS::S3::Bucket            Thu May 21 2020 04:58:23 GMT+0000 (Coordinated Universal Time)                            
CREATE_IN_PROGRESS AuthRole                    AWS::IAM::Role             Thu May 21 2020 04:58:23 GMT+0000 (Coordinated Universal Time)                            
CREATE_IN_PROGRESS amplify-eventapp-deva-45819 AWS::CloudFormation::Stack Thu May 21 2020 04:58:19 GMT+0000 (Coordinated Universal Time) User Initiated             
⠧ Initializing project in the cloud...

CREATE_IN_PROGRESS DeploymentBucket AWS::S3::Bucket Thu May 21 2020 04:58:25 GMT+0000 (Coordinated Universal Time) Resource creation Initiated
⠼ Initializing project in the cloud...

CREATE_COMPLETE UnauthRole AWS::IAM::Role Thu May 21 2020 04:58:42 GMT+0000 (Coordinated Universal Time) 
CREATE_COMPLETE AuthRole   AWS::IAM::Role Thu May 21 2020 04:58:42 GMT+0000 (Coordinated Universal Time) 
⠦ Initializing project in the cloud...

CREATE_COMPLETE amplify-eventapp-deva-45819 AWS::CloudFormation::Stack Thu May 21 2020 04:58:49 GMT+0000 (Coordinated Universal Time) 
CREATE_COMPLETE DeploymentBucket            AWS::S3::Bucket            Thu May 21 2020 04:58:46 GMT+0000 (Coordinated Universal Time) 
✔ Successfully created initial AWS cloud resources for deployments.
✔ Initialized provider successfully.
? Do you want to configure Lambda Triggers for Cognito? Yes
? Which triggers do you want to enable for Cognito 
? Enter the name of the group to which users will be added. users
Initialized your environment successfully.

Your project has been successfully initialized and connected to the cloud!

Some next steps:
"amplify status" will show you what you've added already and if it's locally configured or deployed
"amplify add <category>" will allow you to add features like user login or a backend API
"amplify push" will build all your local backend resources and provision it in the cloud
"amplify console" to open the Amplify Console and view your project status
"amplify publish" will build all your local backend and frontend resources (if you have hosting category added) and provision it in the cloud

Pro tip:
Try "amplify add api" to create a backend API and then "amplify publish" to deploy everything

ec2-user@7bbe1f6e7523:/code$ amplify status

Current Environment: deva

| Category  | Resource name                    | Operation | Provider plugin   |
| --------- | -------------------------------- | --------- | ----------------- |
| Auth      | eventappfb982ea6                 | Create    | awscloudformation |
| Function  | eventappfb982ea6PostConfirmation | Create    | awscloudformation |
| Api       | eventapp                         | Create    | awscloudformation |
| Analytics | eventapp                         | Create    | awscloudformation |


**ec2-user@7bbe1f6e7523:/code$ amplify push**
✔ Successfully pulled backend environment deva from the cloud.

Current Environment: deva

| Category  | Resource name                    | Operation | Provider plugin   |
| --------- | -------------------------------- | --------- | ----------------- |
| Auth      | eventappfb982ea6                 | Create    | awscloudformation |
| Function  | eventappfb982ea6PostConfirmation | Create    | awscloudformation |
| Api       | eventapp                         | Create    | awscloudformation |
| Analytics | eventapp                         | Create    | awscloudformation |
? Are you sure you want to continue? Yes

The following types do not have '@auth' enabled. Consider using @auth with @model
         - User
         - Event
         - Chat
         - Follower
Learn more about @auth here: https://docs.amplify.aws/cli/graphql-transformer/directives#auth


GraphQL schema compiled successfully.

Edit your schema at /code/amplify/backend/api/eventapp/schema.graphql or place .graphql files in a directory at /code/amplify/backend/api/eventapp/schema
? Do you want to update code for your updated GraphQL API Yes
? Do you want to generate GraphQL statements (queries, mutations and subscription) based on your schema types?
This will overwrite your current graphql queries, mutations and subscriptions Yes
⠋ Updating resources in the cloud. This may take a few minutes...
`

**And then, after a lot of "CREATE_IN_PROGRESS" I got this:**

`CREATE_COMPLETE amplify-eventapp-deva-45819-apieventapp-1UVCWV0IMFWC1-CustomResourcesjson-1QDXD2RC15TCD AWS::CloudFormation::Stack Thu May 21 2020 05:08:22 GMT+0000 (Coordinated Universal Time) 
⠧ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE CustomResourcesjson AWS::CloudFormation::Stack Thu May 21 2020 05:08:29 GMT+0000 (Coordinated Universal Time) 
⠇ Updating resources in the cloud. This may take a few minutes...

CREATE_COMPLETE apieventapp AWS::CloudFormation::Stack Thu May 21 2020 05:08:32 GMT+0000 (Coordinated Universal Time) 
⠋ Updating resources in the cloud. This may take a few minutes...

UPDATE_COMPLETE                     amplify-eventapp-deva-45819 AWS::CloudFormation::Stack Thu May 21 2020 05:08:37 GMT+0000 (Coordinated Universal Time) 
UPDATE_COMPLETE_CLEANUP_IN_PROGRESS amplify-eventapp-deva-45819 AWS::CloudFormation::Stack Thu May 21 2020 05:08:36 GMT+0000 (Coordinated Universal Time) 
✔ Generated GraphQL operations successfully and saved at src/graphql
✔ All resources are updated in the cloud`

**Comment by ykbryan** [comment]
@prakash-mu make sure u have disable the credential rotation in cloud9
