### ISSUE TITLE
Unable to resolve "native-base/Fonts/Roboto.ttf" from "App.js"

### ISSUE THREAD

**Issue by prakash-mu** [aws-samples/aws-amplify-react-native-events-app-workshop#5]
When I launch the app in Expo on iPhone, I get the below error. I see that the file is not in my package.

Unable to resolve "native-base/Fonts/Roboto.ttf" from "App.js"
Failed building JavaScript bundle.
Unable to resolve "native-base/Fonts/Roboto.ttf" from "App.js"
Failed building JavaScript bundle.

I see this part of the code in app.js but there is no Roboro.ttf file in native-base/Fonts/Roboto.ttf

function App() {
  const [appState, setAppState] = useState(AppState.currentState);
  const [isLoading, setIsLoading] = useState(true);
  const navigationRef = useRef();
  const routeNameRef = useRef();

  const loadFonts = async () => {
    // for native-base
    await Font.loadAsync({
      Roboto: require('native-base/Fonts/Roboto.ttf'),
      Roboto_medium: require('native-base/Fonts/Roboto_medium.ttf'),
      ...Ionicons.font,
    });
    setIsLoading(!isLoading);
  };

  useEffect(() => {
    loadFonts();

**Comment by ykbryan** [comment]
Resolved. 
Closing this issue.
